# Generated by Django 2.1.1 on 2018-10-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='zip_code',
            new_name='address_zip',
        ),
    ]
