# Generated by Django 2.1.1 on 2018-10-28 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 28, 18, 47, 9, 945434, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
