# Generated by Django 2.1.1 on 2018-10-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-timestamp']},
        ),
    ]
