# Generated by Django 2.1.1 on 2018-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='expired',
            field=models.IntegerField(default=1),
        ),
    ]
