# Generated by Django 2.1.1 on 2018-11-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181101_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='expired',
            field=models.IntegerField(default=3),
        ),
    ]
