# Generated by Django 2.1.1 on 2018-10-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('', '--- --- ---'), ('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120)),
                ('address_1', models.CharField(max_length=120)),
                ('address_2', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('postal_code', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
